
/**
 * GLSLConverter - Handles conversion of Slang GLSL to WebGL GLSL
 */

import { ShaderParameter, GlobalDefinitions, SlangShaderCompiler } from './SlangShaderCompiler';

export class GLSLConverter {
  /**
   * Convert Slang GLSL to WebGL GLSL
   */
  public static convert(
    source: string,
    stage: 'vertex' | 'fragment',
    webgl2: boolean,
    parameters: ShaderParameter[] = [],
    globalDefs: GlobalDefinitions = { functions: [], defines: [], consts: [], globals: [] },
    preserveUBOs: boolean = false
  ): string {
    let output = source;

    // Replace #version
    if (webgl2) {
      output = output.replace(/#version\s+\d+/, '#version 300 es');
    } else {
      output = output.replace(/#version\s+\d+/, '');
    }

    // Strip #pragma parameter lines (they become uniforms instead)
    output = output.replace(/#pragma\s+parameter\s+.*$/gm, '');

    // Strip #define directives that alias UBO members (we're converting UBO to individual uniforms)
    // Common patterns: #define SourceSize params.OriginalSize, #define MVP global.MVP
    const uboDefines = /^\s*#define\s+(SourceSize|OriginalSize|OriginalFeedbackSize|OutputSize|FinalViewportSize|DerezedPassSize|FrameCount|FrameDirection|MVP)\s+.*$/gm;
    output = output.replace(uboDefines, '');

    // Add precision (both vertex and fragment need it for uniform injection)
    const precisionLine = webgl2
      ? 'precision highp float;\nprecision highp int;\n'
      : 'precision mediump float;\n';

    // Insert after #version
    const versionMatch = output.match(/#version.*?\n/);
    if (versionMatch) {
      output = output.replace(versionMatch[0], versionMatch[0] + precisionLine);
    } else {
      output = precisionLine + output;
    }

    // Inject global definitions after precision declarations
    const globalDefsCode = SlangShaderCompiler.buildGlobalDefinitionsCode(globalDefs, output, stage);
    if (globalDefsCode) {
      console.log(`[GLSLConverter] Injecting ${globalDefs.defines.length + globalDefs.consts.length + globalDefs.globals.length + globalDefs.functions.length} global definitions into ${stage} stage`);

      // Find insertion point: after precision declarations
      const precisionEnd = output.search(/precision.*?;\s*\n\s*precision.*?;\s*\n|precision.*?;\s*\n/);
      if (precisionEnd !== -1) {
        const precisionMatch = output.substring(precisionEnd).match(/precision.*?;\s*\n/);
        if (precisionMatch) {
          const insertPos = precisionEnd + precisionMatch[0].length;
          output = output.substring(0, insertPos) + '\n' + globalDefsCode + '\n' + output.substring(insertPos);
        }
      } else {
        // No precision found, insert after #version
        const versionEnd = output.search(/#version.*?\n/);
        if (versionEnd !== -1) {
          const versionMatch = output.match(/#version.*?\n/);
          if (versionMatch) {
            const insertPos = versionEnd + versionMatch[0].length;
            output = output.substring(0, insertPos) + '\n' + globalDefsCode + '\n' + output.substring(insertPos);
          }
        }
      }
    }

    // Add RetroArch params and shader parameter uniforms
    // Extract existing UBO/push constant member names to avoid redefinition
    const existingMembers = new Set<string>();

    console.log(`[GLSLConverter] Stage conversion - found ${existingMembers.size} existing binding members`);
    console.log(`[GLSLConverter] Stage conversion - processing ${parameters.length} shader parameters`);

    // Build parameter uniforms (skip if already in UBO/push constant OR duplicate in parameters array)
    const seenParams = new Set<string>();
    const filtered = parameters.filter(param => {
      if (existingMembers.has(param.name)) return false; // Already in UBO/push constant
      if (seenParams.has(param.name)) {
        console.log(`[GLSLConverter] Skipping duplicate parameter: ${param.name}`);
        return false; // Duplicate in parameters array
      }
      seenParams.add(param.name);
      return true;
    });

    const skippedInBindings = parameters.filter(param => existingMembers.has(param.name));
    if (skippedInBindings.length > 0) {
      console.log(`[GLSLConverter] Skipping ${skippedInBindings.length} parameters already in bindings:`, skippedInBindings.map(p => p.name).slice(0, 20).join(', '), '...');
    }

    const paramUniforms = filtered
      .map(param => `uniform float ${param.name};`)
      .join('\n');

    // Mega Bezel parameters - injected as mutable variables, not uniforms
    // Most HSM parameters need to be assignable variables, not read-only uniforms
    let megaBezelVariables = '';

    if (stage === 'fragment') {
      megaBezelVariables = `
float HSM_AB_COMPARE_AREA = 0.0;
uniform float HSM_AB_COMPARE_FREEZE_CRT_TUBE;
uniform float HSM_AB_COMPARE_FREEZE_GRAPHICS;
uniform float HSM_AB_COMPARE_SHOW_MODE;
uniform float HSM_AB_COMPARE_SPLIT_POSITION;
uniform float HSM_AMBIENT_LIGHTING_OPACITY;
uniform float HSM_AMBIENT_LIGHTING_SWAP_IMAGE_MODE;
uniform float HSM_AMBIENT1_CONTRAST;
uniform float HSM_AMBIENT1_DITHERING_SAMPLES;
uniform float HSM_AMBIENT1_HUE;
uniform float HSM_AMBIENT1_MIRROR_HORZ;
uniform float HSM_AMBIENT1_OPACITY;
uniform float HSM_AMBIENT1_POSITION_X;
uniform float HSM_AMBIENT1_POSITION_Y;
uniform float HSM_AMBIENT1_POS_INHERIT_MODE;
uniform float HSM_AMBIENT1_ROTATE;
uniform float HSM_AMBIENT1_SATURATION;
uniform float HSM_AMBIENT1_SCALE;
uniform float HSM_AMBIENT1_SCALE_INHERIT_MODE;
uniform float HSM_AMBIENT1_SCALE_KEEP_ASPECT;
uniform float HSM_AMBIENT1_SCALE_X;
uniform float HSM_AMBIENT1_VALUE;
uniform float HSM_AMBIENT2_CONTRAST;
uniform float HSM_AMBIENT2_HUE;
uniform float HSM_AMBIENT2_MIRROR_HORZ;
uniform float HSM_AMBIENT2_OPACITY;
uniform float HSM_AMBIENT2_POSITION_X;
uniform float HSM_AMBIENT2_POSITION_Y;
uniform float HSM_AMBIENT2_POS_INHERIT_MODE;
uniform float HSM_AMBIENT2_ROTATE;
uniform float HSM_AMBIENT2_SATURATION;
uniform float HSM_AMBIENT2_SCALE;
uniform float HSM_AMBIENT2_SCALE_INHERIT_MODE;
uniform float HSM_AMBIENT2_SCALE_KEEP_ASPECT;
uniform float HSM_AMBIENT2_SCALE_X;
uniform float HSM_AMBIENT2_VALUE;
uniform float HSM_ANTI_FLICKER_ON;
uniform float HSM_ANTI_FLICKER_THRESHOLD;
uniform float HSM_ASPECT_RATIO_EXPLICIT;
uniform float HSM_ASPECT_RATIO_MODE;
uniform float HSM_ASPECT_RATIO_ORIENTATION;
uniform float HSM_BG_AMBIENT_LIGHTING_MULTIPLIER;
uniform float HSM_BG_APPLY_AMBIENT_IN_ADD_MODE;
uniform float HSM_BG_BLEND_MODE;
uniform float HSM_BG_BRIGHTNESS;
uniform float HSM_BG_COLORIZE_ON;
uniform float HSM_BG_CUTOUT_MODE;
uniform float HSM_BG_DUALSCREEN_VIS_MODE;
uniform float HSM_BG_FILL_MODE;
uniform float HSM_BG_FOLLOW_FULL_USES_ZOOM;
uniform float HSM_BG_FOLLOW_LAYER;
uniform float HSM_BG_FOLLOW_MODE;
uniform float HSM_BG_GAMMA;
uniform float HSM_BG_HUE;
uniform float HSM_BG_LAYER_ORDER;
uniform float HSM_BG_MASK_MODE;
uniform float HSM_BG_MIPMAPPING_BLEND_BIAS;
uniform float HSM_BG_OPACITY;
uniform float HSM_BG_POS_X;
uniform float HSM_BG_POS_Y;
uniform float HSM_BG_SATURATION;
uniform float HSM_BG_SCALE;
uniform float HSM_BG_SCALE_X;
uniform float HSM_BG_SOURCE_MATTE_TYPE;
uniform float HSM_BG_SPLIT_PRESERVE_CENTER;
uniform float HSM_BG_SPLIT_REPEAT_WIDTH;
uniform float HSM_BG_WRAP_MODE;
uniform float HSM_BZL_AMBIENT_LIGHTING_MULTIPLIER;
uniform float HSM_BZL_AMBIENT2_LIGHTING_MULTIPLIER;
uniform float HSM_BZL_BLEND_MODE;
uniform float HSM_BZL_BRIGHTNESS;
uniform float HSM_BZL_BRIGHTNESS_MULT_BOTTOM;
uniform float HSM_BZL_BRIGHTNESS_MULT_SIDE_LEFT;
uniform float HSM_BZL_BRIGHTNESS_MULT_SIDE_RIGHT;
uniform float HSM_BZL_BRIGHTNESS_MULT_SIDES;
uniform float HSM_BZL_BRIGHTNESS_MULT_TOP;
uniform float HSM_BZL_COLOR_HUE;
uniform float HSM_BZL_COLOR_SATURATION;
uniform float HSM_BZL_COLOR_VALUE;
uniform float HSM_BZL_HEIGHT;
uniform float HSM_BZL_HIGHLIGHT;
uniform float HSM_BZL_INDEPENDENT_CURVATURE_SCALE_LONG_AXIS;
uniform float HSM_BZL_INDEPENDENT_CURVATURE_SCALE_SHORT_AXIS;
uniform float HSM_BZL_INDEPENDENT_SCALE;
uniform float HSM_BZL_INNER_CORNER_RADIUS_SCALE;
uniform float HSM_BZL_INNER_CURVATURE_SCALE;
uniform float HSM_BZL_INNER_EDGE_HIGHLIGHT;
uniform float HSM_BZL_INNER_EDGE_SHADOW;
uniform float HSM_BZL_INNER_EDGE_SHARPNESS;
uniform float HSM_BZL_INNER_EDGE_THICKNESS;
uniform float HSM_BZL_NOISE;
uniform float HSM_BZL_OPACITY;
uniform float HSM_BZL_OUTER_CORNER_RADIUS_SCALE;
uniform float HSM_BZL_OUTER_CURVATURE_SCALE;
uniform float HSM_BZL_OUTER_POSITION_Y;
uniform float HSM_BZL_SCALE_OFFSET;
uniform float HSM_BZL_USE_INDEPENDENT_CURVATURE;
uniform float HSM_BZL_USE_INDEPENDENT_SCALE;
uniform float HSM_BZL_WIDTH;
uniform float HSM_CACHE_GRAPHICS_ON;
uniform float HSM_CACHE_UPDATE_INDICATOR_MODE;
uniform float HSM_CORE_RES_SAMPLING_MULT_OPPOSITE_DIR;
uniform float HSM_CORE_RES_SAMPLING_MULT_SCANLINE_DIR;
uniform float HSM_CROP_BLACK_THRESHOLD;
uniform float HSM_CROP_MODE;
uniform float HSM_CROP_PERCENT_BOTTOM;
uniform float HSM_CROP_PERCENT_LEFT;
uniform float HSM_CROP_PERCENT_RIGHT;
uniform float HSM_CROP_PERCENT_TOP;
uniform float HSM_CROP_PERCENT_ZOOM;
uniform float HSM_CRT_BLEND_AMOUNT;
uniform float HSM_CRT_BLEND_MODE;
uniform float HSM_CRT_CURVATURE_SCALE;
uniform float HSM_CRT_SCREEN_BLEND_MODE;
uniform float HSM_CURVATURE_2D_SCALE_LONG_AXIS;
uniform float HSM_CURVATURE_2D_SCALE_SHORT_AXIS;
uniform float HSM_CURVATURE_3D_RADIUS;
uniform float HSM_CURVATURE_3D_TILT_ANGLE_X;
uniform float HSM_CURVATURE_3D_TILT_ANGLE_Y;
uniform float HSM_CURVATURE_3D_VIEW_DIST;
uniform float HSM_CURVATURE_MODE;
uniform float HSM_DOWNSAMPLE_BLUR_OPPOSITE_DIR;
uniform float HSM_DOWNSAMPLE_BLUR_SCANLINE_DIR;
uniform float HSM_DREZ_HSHARP0;
uniform float HSM_DREZ_SIGMA_HV;
uniform float HSM_DREZ_SHAR;
uniform float HSM_DREZ_THRESHOLD_RATIO;
uniform float HSM_DUALSCREEN_CORE_IMAGE_SPLIT_MODE;
uniform float HSM_DUALSCREEN_CORE_IMAGE_SWAP_SCREENS;
uniform float HSM_DUALSCREEN_CORE_IMAGE_SPLIT_OFFSET;
uniform float HSM_DUALSCREEN_MODE;
uniform float HSM_DUALSCREEN_POSITION_OFFSET_BETWEEN_SCREENS;
uniform float HSM_DUALSCREEN_SHIFT_POSITION_WITH_SCALE;
uniform float HSM_DUALSCREEN_VIEWPORT_SPLIT_LOCATION;
uniform float HSM_FAKE_SCANLINE_CURVATURE;
uniform float HSM_FAKE_SCANLINE_INT_SCALE;
uniform float HSM_FAKE_SCANLINE_MODE;
uniform float HSM_FAKE_SCANLINE_OPACITY;
uniform float HSM_FAKE_SCANLINE_RES;
uniform float HSM_FAKE_SCANLINE_RES_MODE;
uniform float HSM_FAKE_SCANLINE_ROLL;
uniform float HSM_FLIP_CORE_HORIZONTAL;
uniform float HSM_FLIP_CORE_VERTICAL;
uniform float HSM_FLIP_VIEWPORT_HORIZONTAL;
uniform float HSM_FLIP_VIEWPORT_VERTICAL;
uniform float HSM_FRM_BLEND_MODE;
uniform float HSM_FRM_COLOR_HUE;
uniform float HSM_FRM_COLOR_SATURATION;
uniform float HSM_FRM_COLOR_VALUE;
uniform float HSM_FRM_INNER_EDGE_HIGHLIGHT;
uniform float HSM_FRM_INNER_EDGE_THICKNESS;
uniform float HSM_FRM_NOISE;
uniform float HSM_FRM_OPACITY;
uniform float HSM_FRM_OUTER_CORNER_RADIUS;
uniform float HSM_FRM_OUTER_CURVATURE_SCALE;
uniform float HSM_FRM_OUTER_EDGE_SHADING;
uniform float HSM_FRM_OUTER_EDGE_THICKNESS;
uniform float HSM_FRM_OUTER_POS_Y;
uniform float HSM_FRM_SHADOW_OPACITY;
uniform float HSM_FRM_SHADOW_WIDTH;
uniform float HSM_FRM_TEXTURE_BLEND_MODE;
uniform float HSM_FRM_TEXTURE_OPACITY;
uniform float HSM_FRM_THICKNESS;
uniform float HSM_FRM_THICKNESS_SCALE_X;
uniform float HSM_FRM_USE_INDEPENDENT_COLOR;
uniform float HSM_GLOBAL_CORNER_RADIUS;
uniform float HSM_GLOBAL_GRAPHICS_BRIGHTNESS;
uniform float HSM_INT_SCALE_MAX_HEIGHT;
uniform float HSM_INT_SCALE_MODE;
uniform float HSM_INT_SCALE_MULTIPLE_OFFSET;
uniform float HSM_INT_SCALE_MULTIPLE_OFFSET_LONG;
uniform float HSM_INTERLACE_EFFECT_SMOOTHNESS_INTERS;
uniform float HSM_INTERLACE_MODE;
uniform float HSM_INTERLACE_SCANLINE_EFFECT;
uniform float HSM_INTERLACE_TRIGGER_RES;
uniform float HSM_INTRO_LOGO_BLEND_MODE;
uniform float HSM_INTRO_LOGO_FADE_IN;
uniform float HSM_INTRO_LOGO_FADE_OUT;
uniform float HSM_INTRO_LOGO_FLIP_VERTICAL;
uniform float HSM_INTRO_LOGO_HEIGHT;
uniform float HSM_INTRO_LOGO_HOLD;
uniform float HSM_INTRO_LOGO_OVER_SOLID_COLOR;
uniform float HSM_INTRO_LOGO_PLACEMENT;
uniform float HSM_INTRO_LOGO_POS_X;
uniform float HSM_INTRO_LOGO_POS_Y;
uniform float HSM_INTRO_LOGO_WAIT;
uniform float HSM_INTRO_NOISE_BLEND_MODE;
uniform float HSM_INTRO_NOISE_FADE_OUT;
uniform float HSM_INTRO_NOISE_HOLD;
uniform float HSM_INTRO_SOLID_BLACK_FADE_OUT;
uniform float HSM_INTRO_SOLID_BLACK_HOLD;
uniform float HSM_INTRO_SOLID_COLOR_BLEND_MODE;
uniform float HSM_INTRO_SOLID_COLOR_FADE_OUT;
uniform float HSM_INTRO_SOLID_COLOR_HOLD;
uniform float HSM_INTRO_SOLID_COLOR_HUE;
uniform float HSM_INTRO_SOLID_COLOR_SAT;
uniform float HSM_INTRO_SOLID_COLOR_VALUE;
uniform float HSM_INTRO_SPEED;
uniform float HSM_INTRO_WHEN_TO_SHOW;
uniform float HSM_LAYERING_DEBUG_MASK_MODE;
uniform float HSM_LED_AMBIENT_LIGHTING_MULTIPLIER;
uniform float HSM_LED_APPLY_AMBIENT_IN_ADD_MODE;
uniform float HSM_LED_BLEND_MODE;
uniform float HSM_LED_BRIGHTNESS;
uniform float HSM_LED_COLORIZE_ON;
uniform float HSM_LED_CUTOUT_MODE;
uniform float HSM_LED_DUALSCREEN_VIS_MODE;
uniform float HSM_LED_FILL_MODE;
uniform float HSM_LED_FOLLOW_FULL_USES_ZOOM;
uniform float HSM_LED_FOLLOW_LAYER;
uniform float HSM_LED_FOLLOW_MODE;
uniform float HSM_LED_GAMMA;
uniform float HSM_LED_HUE;
uniform float HSM_LED_LAYER_ORDER;
uniform float HSM_LED_MASK_MODE;
uniform float HSM_LED_MIPMAPPING_BLEND_BIAS;
uniform float HSM_LED_OPACITY;
uniform float HSM_LED_POS_X;
uniform float HSM_LED_POS_Y;
uniform float HSM_LED_SATURATION;
uniform float HSM_LED_SCALE;
uniform float HSM_LED_SCALE_X;
uniform float HSM_LED_SOURCE_MATTE_TYPE;
uniform float HSM_LED_SPLIT_PRESERVE_CENTER;
uniform float HSM_LED_SPLIT_REPEAT_WIDTH;
uniform float HSM_MONOCHROME_BRIGHTNESS;
uniform float HSM_MONOCHROME_DUALSCREEN_VIS_MODE;
uniform float HSM_MONOCHROME_GAMMA;
uniform float HSM_MONOCHROME_HUE_OFFSET;
uniform float HSM_MONOCHROME_MODE;
uniform float HSM_MONOCHROME_SATURATION;
uniform float HSM_NON_INTEGER_SCALE;
uniform float HSM_NON_INTEGER_SCALE_OFFSET;
uniform float HSM_OVERSCAN_AMOUNT;
uniform float HSM_OVERSCAN_RASTER_BLOOM_AMOUNT;
uniform float HSM_OVERSCAN_RASTER_BLOOM_MODE;
uniform float HSM_OVERSCAN_RASTER_BLOOM_NEUTRAL_RANGE;
uniform float HSM_OVERSCAN_RASTER_BLOOM_NEUTRAL_RANGE_CENTER;
uniform float HSM_OVERSCAN_RASTER_BLOOM_ON;
uniform float HSM_OVERSCAN_X;
uniform float HSM_OVERSCAN_Y;
uniform float HSM_PASS_VIEWER_EMPTY_LINE;
uniform float HSM_PASS_VIEWER_TITLE;
uniform float HSM_PHYSICAL_MONITOR_ASPECT_RATIO;
uniform float HSM_PHYSICAL_MONITOR_DIAGONAL_SIZE;
uniform float HSM_PHYSICAL_MONITOR_DIAGONAL_SIZE;
uniform float HSM_PLACEMENT_IMAGE_MODE;
uniform float HSM_PLACEMENT_IMAGE_USE_HORIZONTAL;
uniform float HSM_POST_CRT_BRIGHTNESS;
uniform float HSM_POTATO_COLORIZE_BRIGHTNESS;
uniform float HSM_POTATO_COLORIZE_CRT_WITH_BG;
uniform float HSM_POTATO_SHOW_BG_OVER_SCREEN;
uniform float HSM_REFLECT_BEZEL_INNER_EDGE_AMOUNT;
uniform float HSM_REFLECT_BEZEL_INNER_EDGE_FULLSCREEN_GLOW;
uniform float HSM_REFLECT_BLUR_FALLOFF_DISTANCE;
uniform float HSM_REFLECT_BLUR_MAX;
uniform float HSM_REFLECT_BLUR_MIN;
uniform float HSM_REFLECT_BLUR_NUM_SAMPLES;
uniform float HSM_REFLECT_BRIGHTNESS_NOISE_BLACK_LEVEL;
uniform float HSM_REFLECT_BRIGHTNESS_NOISE_BRIGHTNESS;
uniform float HSM_REFLECT_CORNER_FADE;
uniform float HSM_REFLECT_CORNER_FADE_DISTANCE;
uniform float HSM_REFLECT_CORNER_INNER_SPREAD;
uniform float HSM_REFLECT_CORNER_OUTER_SPREAD;
uniform float HSM_REFLECT_CORNER_ROTATION_OFFSET_BOTTOM;
uniform float HSM_REFLECT_CORNER_ROTATION_OFFSET_TOP;
uniform float HSM_REFLECT_CORNER_SPREAD_FALLOFF;
uniform float HSM_REFLECT_DIFFUSED_AMOUNT;
uniform float HSM_REFLECT_DIRECT_AMOUNT;
uniform float HSM_REFLECT_FADE_AMOUNT;
uniform float HSM_REFLECT_FRAME_INNER_EDGE_AMOUNT;
uniform float HSM_REFLECT_FRAME_INNER_EDGE_SHARPNESS;
uniform float HSM_REFLECT_FULLSCREEN_GLOW;
uniform float HSM_REFLECT_FULLSCREEN_GLOW_GAMMA;
uniform float HSM_REFLECT_GLOBAL_AMOUNT;
uniform float HSM_REFLECT_GLOBAL_GAMMA_ADJUST;
uniform float HSM_REFLECT_LATERAL_OUTER_FADE_DISTANCE;
uniform float HSM_REFLECT_LATERAL_OUTER_FADE_POSITION;
uniform float HSM_REFLECT_MASK_BLACK_LEVEL;
uniform float HSM_REFLECT_MASK_BRIGHTNESS;
uniform float HSM_REFLECT_MASK_FOLLOW_LAYER;
uniform float HSM_REFLECT_MASK_FOLLOW_MODE;
uniform float HSM_REFLECT_MASK_IMAGE_AMOUNT;
uniform float HSM_REFLECT_MASK_MIPMAPPING_BLEND_BIAS;
uniform float HSM_REFLECT_NOISE_AMOUNT;
uniform float HSM_REFLECT_NOISE_SAMPLE_DISTANCE;
uniform float HSM_REFLECT_NOISE_SAMPLES;
uniform float HSM_REFLECT_RADIAL_FADE_HEIGHT;
uniform float HSM_REFLECT_RADIAL_FADE_WIDTH;
uniform float HSM_REFLECT_SHOW_TUBE_FX_AMOUNT;
uniform float HSM_REFLECT_VIGNETTE_AMOUNT;
uniform float HSM_REFLECT_VIGNETTE_SIZE;
uniform float HSM_RENDER_FOR_SIMPLIFIED_EMPTY_LINE;
uniform float HSM_RENDER_FOR_SIMPLIFIED_TITLE;
uniform float HSM_RENDER_SIMPLE_MASK_TYPE;
uniform float HSM_RENDER_SIMPLE_MODE;
uniform float HSM_RESOLUTION_DEBUG_ON;
uniform float HSM_ROTATE_CORE_IMAGE;
uniform float HSM_SCANLINE_DIRECTION;
uniform float HSM_SCREEN_CORNER_RADIUS_SCALE;
uniform float HSM_SCREEN_POSITION_X;
uniform float HSM_SCREEN_POSITION_Y;
uniform float HSM_SCREEN_REFLECTION_FOLLOW_DIFFUSE_THICKNESS;
uniform float HSM_SCREEN_REFLECTION_POS_X;
uniform float HSM_SCREEN_REFLECTION_POS_Y;
uniform float HSM_SCREEN_REFLECTION_SCALE;
uniform float HSM_SCREEN_VIGNETTE_DUALSCREEN_VIS_MODE;
uniform float HSM_SCREEN_VIGNETTE_IN_REFLECTION;
uniform float HSM_SCREEN_VIGNETTE_ON;
uniform float HSM_SCREEN_VIGNETTE_POWER;
uniform float HSM_SCREEN_VIGNETTE_STRENGTH;
uniform float HSM_SHOW_CRT_ON_TOP_OF_COLORED_GEL;
uniform float HSM_SHOW_PASS_ALPHA;
uniform float HSM_SHOW_PASS_APPLY_SCREEN_COORD;
uniform float HSM_SHOW_PASS_INDEX;
uniform float HSM_SIGNAL_NOISE_AMOUNT;
uniform float HSM_SIGNAL_NOISE_BLACK_LEVEL;
uniform float HSM_SIGNAL_NOISE_ON;
uniform float HSM_SIGNAL_NOISE_SIZE_MODE;
uniform float HSM_SIGNAL_NOISE_SIZE_MULT;
uniform float HSM_SIGNAL_NOISE_TYPE;
uniform float HSM_SINDEN_BORDER_BRIGHTNESS;
uniform float HSM_SINDEN_BORDER_EMPTY_TUBE_COMPENSATION;
uniform float HSM_SINDEN_BORDER_ON;
uniform float HSM_SINDEN_BORDER_THICKNESS;
uniform float HSM_SNAP_TO_CLOSEST_INT_SCALE_TOLERANCE;
uniform float HSM_STATIC_LAYERS_GAMMA;
uniform float HSM_TOP_AMBIENT_LIGHTING_MULTIPLIER;
uniform float HSM_TOP_APPLY_AMBIENT_IN_ADD_MODE;
uniform float HSM_TOP_BLEND_MODE;
uniform float HSM_TOP_BRIGHTNESS;
uniform float HSM_TOP_COLORIZE_ON;
uniform float HSM_TOP_CUTOUT_MODE;
uniform float HSM_TOP_DUALSCREEN_VIS_MODE;
uniform float HSM_TOP_FILL_MODE;
uniform float HSM_TOP_FOLLOW_FULL_USES_ZOOM;
uniform float HSM_TOP_FOLLOW_LAYER;
uniform float HSM_TOP_FOLLOW_MODE;
uniform float HSM_TOP_GAMMA;
uniform float HSM_TOP_HUE;
uniform float HSM_TOP_LAYER_ORDER;
uniform float HSM_TOP_MASK_MODE;
uniform float HSM_TOP_MIPMAPPING_BLEND_BIAS;
uniform float HSM_TOP_OPACITY;
uniform float HSM_TOP_POS_X;
uniform float HSM_TOP_POS_Y;
uniform float HSM_TOP_SATURATION;
uniform float HSM_TOP_SCALE;
uniform float HSM_TOP_SCALE_X;
uniform float HSM_TOP_SOURCE_MATTE_TYPE;
uniform float HSM_TOP_SPLIT_PRESERVE_CENTER;
uniform float HSM_TOP_SPLIT_REPEAT_WIDTH;
uniform float HSM_TUBE_ASPECT_AND_EMPTY_LINE;
uniform float HSM_TUBE_ASPECT_AND_EMPTY_TITLE;
uniform float HSM_TUBE_BLACK_EDGE_CORNER_RADIUS_SCALE;
uniform float HSM_TUBE_BLACK_EDGE_CURVATURE_SCALE;
uniform float HSM_TUBE_BLACK_EDGE_SHARPNESS;
uniform float HSM_TUBE_BLACK_EDGE_THICKNESS;
uniform float HSM_TUBE_BLACK_EDGE_THICKNESS_X_SCALE;
uniform float HSM_TUBE_COLORED_GEL_IMAGE_ADDITIVE_AMOUNT;
uniform float HSM_TUBE_COLORED_GEL_IMAGE_AMBIENT_LIGHTING;
uniform float HSM_TUBE_COLORED_GEL_IMAGE_AMBIENT2_LIGHTING;
uniform float HSM_TUBE_COLORED_GEL_IMAGE_DUALSCREEN_VIS_MODE;
uniform float HSM_TUBE_COLORED_GEL_IMAGE_FAKE_SCANLINE_AMOUNT;
uniform float HSM_TUBE_COLORED_GEL_IMAGE_FLIP_HORIZONTAL;
uniform float HSM_TUBE_COLORED_GEL_IMAGE_FLIP_VERTICAL;
uniform float HSM_TUBE_COLORED_GEL_IMAGE_MULTIPLY_AMOUNT;
uniform float HSM_TUBE_COLORED_GEL_IMAGE_NORMAL_AMOUNT;
uniform float HSM_TUBE_COLORED_GEL_IMAGE_NORMAL_BRIGHTNESS;
uniform float HSM_TUBE_COLORED_GEL_IMAGE_NORMAL_VIGNETTE;
uniform float HSM_TUBE_COLORED_GEL_IMAGE_ON;
uniform float HSM_TUBE_COLORED_GEL_IMAGE_SCALE;
uniform float HSM_TUBE_COLORED_GEL_IMAGE_TRANSPARENCY_THRESHOLD;
uniform float HSM_TUBE_DIFFUSE_FORCE_ASPECT;
uniform float HSM_TUBE_DIFFUSE_IMAGE_AMBIENT_LIGHTING;
uniform float HSM_TUBE_DIFFUSE_IMAGE_AMBIENT2_LIGHTING;
uniform float HSM_TUBE_DIFFUSE_IMAGE_AMOUNT;
uniform float HSM_TUBE_DIFFUSE_IMAGE_BRIGHTNESS;
uniform float HSM_TUBE_DIFFUSE_IMAGE_COLORIZE_ON;
uniform float HSM_TUBE_DIFFUSE_IMAGE_DUALSCREEN_VIS_MODE;
uniform float HSM_TUBE_DIFFUSE_IMAGE_GAMMA;
uniform float HSM_TUBE_DIFFUSE_IMAGE_HUE;
uniform float HSM_TUBE_DIFFUSE_IMAGE_ROTATION;
uniform float HSM_TUBE_DIFFUSE_IMAGE_SATURATION;
uniform float HSM_TUBE_DIFFUSE_IMAGE_SCALE;
uniform float HSM_TUBE_DIFFUSE_IMAGE_SCALE_X;
uniform float HSM_TUBE_DIFFUSE_MODE;
uniform float HSM_TUBE_EMPTY_THICKNESS;
uniform float HSM_TUBE_EMPTY_THICKNESS_X_SCALE;
uniform float HSM_TUBE_OPACITY;
uniform float HSM_TUBE_SHADOW_CURVATURE_SCALE;
uniform float HSM_TUBE_SHADOW_IMAGE_ON;
uniform float HSM_TUBE_SHADOW_IMAGE_OPACITY;
uniform float HSM_TUBE_SHADOW_IMAGE_POS_X;
uniform float HSM_TUBE_SHADOW_IMAGE_POS_Y;
uniform float HSM_TUBE_SHADOW_IMAGE_SCALE_X;
uniform float HSM_TUBE_SHADOW_IMAGE_SCALE_Y;
uniform float HSM_TUBE_STATIC_AMBIENT_LIGHTING;
uniform float HSM_TUBE_STATIC_AMBIENT2_LIGHTING;
uniform float HSM_TUBE_STATIC_BLACK_LEVEL;
uniform float HSM_TUBE_STATIC_DITHER_AMOUNT;
uniform float HSM_TUBE_STATIC_DITHER_DISTANCE;
uniform float HSM_TUBE_STATIC_DITHER_SAMPLES;
uniform float HSM_TUBE_STATIC_OPACITY_DIFFUSE_MULTIPLY;
uniform float HSM_TUBE_STATIC_POS_X;
uniform float HSM_TUBE_STATIC_POS_Y;
uniform float HSM_TUBE_STATIC_REFLECTION_IMAGE_DUALSCREEN_VIS_MODE;
uniform float HSM_TUBE_STATIC_REFLECTION_IMAGE_ON;
uniform float HSM_TUBE_STATIC_REFLECTION_IMAGE_OPACITY;
uniform float HSM_TUBE_STATIC_SCALE;
uniform float HSM_TUBE_STATIC_SCALE_X;
uniform float HSM_TUBE_STATIC_SHADOW_OPACITY;
uniform float HSM_USE_GEOM;
uniform float HSM_USE_IMAGE_FOR_PLACEMENT;
uniform float HSM_USE_PHYSICAL_SIZE_FOR_NON_INTEGER;
uniform float HSM_USE_SNAP_TO_CLOSEST_INT_SCALE;
uniform float HSM_VERTICAL_PRESET;
uniform float HSM_VIEWPORT_POSITION_X;
uniform float HSM_VIEWPORT_POSITION_Y;
uniform float HSM_VIEWPORT_VIGNETTE_CUTOUT_MODE;
uniform float HSM_VIEWPORT_VIGNETTE_FOLLOW_LAYER;
uniform float HSM_VIEWPORT_VIGNETTE_LAYER_ORDER;
uniform float HSM_VIEWPORT_VIGNETTE_MASK_MODE;
uniform float HSM_VIEWPORT_VIGNETTE_OPACITY;
uniform float HSM_VIEWPORT_VIGNETTE_POS_X;
uniform float HSM_VIEWPORT_VIGNETTE_POS_Y;
uniform float HSM_VIEWPORT_VIGNETTE_SCALE;
uniform float HSM_VIEWPORT_VIGNETTE_SCALE_X;
uniform float HSM_VIEWPORT_ZOOM;
uniform float HSM_VIEWPORT_ZOOM_MASK;
uniform float HSM_2ND_SCREEN_ASPECT_RATIO_MODE;
uniform float HSM_2ND_SCREEN_CROP_PERCENT_BOTTOM;
uniform float HSM_2ND_SCREEN_CROP_PERCENT_LEFT;
uniform float HSM_2ND_SCREEN_CROP_PERCENT_RIGHT;
uniform float HSM_2ND_SCREEN_CROP_PERCENT_TOP;
uniform float HSM_2ND_SCREEN_CROP_PERCENT_ZOOM;
uniform float HSM_2ND_SCREEN_INDEPENDENT_SCALE;
uniform float HSM_2ND_SCREEN_POS_X;
uniform float HSM_2ND_SCREEN_POS_Y;
uniform float HSM_2ND_SCREEN_SCALE_OFFSET;
uniform float SCREEN_ASPECT;
uniform vec2 SCREEN_COORD;
uniform float DEFAULT_SRGB_GAMMA;
uniform float GAMMA_INPUT;
uniform float gamma_out;
uniform float post_br;
uniform float post_br_affect_black_level;
uniform float no_scanlines;
uniform float iscans;
uniform float vga_mode;
uniform float hiscan;
uniform float SHARPEN_ON;
uniform float CSHARPEN;
uniform float CCONTR;
uniform float CDETAILS;
uniform float DEBLUR;
uniform float HSM_AB_COMPARE_SPLIT_POSITION;
uniform float HSM_AMBIENT_LIGHTING_OPACITY;
uniform float HSM_AMBIENT_LIGHTING_SWAP_IMAGE_MODE;
uniform float HSM_AMBIENT1_CONTRAST;
uniform float HSM_AMBIENT1_DITHERING_SAMPLES;
uniform float HSM_AMBIENT1_HUE;
uniform float HSM_AMBIENT1_MIRROR_HORZ;
uniform float HSM_AMBIENT1_OPACITY;
uniform float HSM_AMBIENT1_POSITION_X;
uniform float HSM_AMBIENT1_POSITION_Y;
uniform float HSM_AMBIENT1_POS_INHERIT_MODE;
uniform float HSM_AMBIENT1_ROTATE;
uniform float HSM_AMBIENT1_SATURATION;
uniform float HSM_AMBIENT1_SCALE;
uniform float HSM_AMBIENT1_SCALE_INHERIT_MODE;
uniform float HSM_AMBIENT1_SCALE_KEEP_ASPECT;
uniform float HSM_AMBIENT1_SCALE_X;
uniform float HSM_AMBIENT1_VALUE;
uniform float HSM_AMBIENT2_CONTRAST;
uniform float HSM_AMBIENT2_HUE;
uniform float HSM_AMBIENT2_MIRROR_HORZ;
uniform float HSM_AMBIENT2_OPACITY;
uniform float HSM_AMBIENT2_POSITION_X;
uniform float HSM_AMBIENT2_POSITION_Y;
uniform float HSM_AMBIENT2_POS_INHERIT_MODE;
uniform float HSM_AMBIENT2_ROTATE;
uniform float HSM_AMBIENT2_SATURATION;
uniform float HSM_AMBIENT2_SCALE;
uniform float HSM_AMBIENT2_SCALE_INHERIT_MODE;
uniform float HSM_AMBIENT2_SCALE_KEEP_ASPECT;
uniform float HSM_AMBIENT2_SCALE_X;
uniform float HSM_AMBIENT2_VALUE;
uniform float HSM_ANTI_FLICKER_ON;
uniform float HSM_ANTI_FLICKER_THRESHOLD;
uniform float HSM_ASPECT_RATIO_EXPLICIT;
uniform float HSM_ASPECT_RATIO_MODE;
uniform float HSM_ASPECT_RATIO_ORIENTATION;
uniform float HSM_BG_AMBIENT_LIGHTING_MULTIPLIER;
uniform float HSM_BG_APPLY_AMBIENT_IN_ADD_MODE;
uniform float HSM_BG_BLEND_MODE;
uniform float HSM_BG_BRIGHTNESS;
uniform float HSM_BG_COLORIZE_ON;
uniform float HSM_BG_CUTOUT_MODE;
uniform float HSM_BG_DUALSCREEN_VIS_MODE;
uniform float HSM_BG_FILL_MODE;
uniform float HSM_BG_FOLLOW_FULL_USES_ZOOM;
uniform float HSM_BG_FOLLOW_LAYER;
uniform float HSM_BG_FOLLOW_MODE;
uniform float HSM_BG_GAMMA;
uniform float HSM_BG_HUE;
uniform float HSM_BG_LAYER_ORDER;
uniform float HSM_BG_MASK_MODE;
uniform float HSM_BG_MIPMAPPING_BLEND_BIAS;
uniform float HSM_BG_OPACITY;
uniform float HSM_BG_POS_X;
uniform float HSM_BG_POS_Y;
uniform float HSM_BG_SATURATION;
uniform float HSM_BG_SCALE;
uniform float HSM_BG_SCALE_X;
uniform float HSM_BG_SOURCE_MATTE_TYPE;
uniform float HSM_BG_SPLIT_PRESERVE_CENTER;
uniform float HSM_BG_SPLIT_REPEAT_WIDTH;
uniform float HSM_BG_WRAP_MODE;
uniform float HSM_BZL_AMBIENT_LIGHTING_MULTIPLIER;
uniform float HSM_BZL_AMBIENT2_LIGHTING_MULTIPLIER;
uniform float HSM_BZL_BLEND_MODE;
uniform float HSM_BZL_BRIGHTNESS;
uniform float HSM_BZL_BRIGHTNESS_MULT_BOTTOM;
uniform float HSM_BZL_BRIGHTNESS_MULT_SIDE_LEFT;
uniform float HSM_BZL_BRIGHTNESS_MULT_SIDE_RIGHT;
uniform float HSM_BZL_BRIGHTNESS_MULT_SIDES;
uniform float HSM_BZL_BRIGHTNESS_MULT_TOP;
uniform float HSM_BZL_COLOR_HUE;
uniform float HSM_BZL_COLOR_SATURATION;
uniform float HSM_BZL_COLOR_VALUE;
uniform float HSM_BZL_HEIGHT;
uniform float HSM_BZL_HIGHLIGHT;
uniform float HSM_BZL_INDEPENDENT_CURVATURE_SCALE_LONG_AXIS;
uniform float HSM_BZL_INDEPENDENT_CURVATURE_SCALE_SHORT_AXIS;
uniform float HSM_BZL_INDEPENDENT_SCALE;
uniform float HSM_BZL_INNER_CORNER_RADIUS_SCALE;
uniform float HSM_BZL_INNER_CURVATURE_SCALE;
uniform float HSM_BZL_INNER_EDGE_HIGHLIGHT;
uniform float HSM_BZL_INNER_EDGE_SHADOW;
uniform float HSM_BZL_INNER_EDGE_SHARPNESS;
uniform float HSM_BZL_INNER_EDGE_THICKNESS;
uniform float HSM_BZL_NOISE;
uniform float HSM_BZL_OPACITY;
uniform float HSM_BZL_OUTER_CORNER_RADIUS_SCALE;
uniform float HSM_BZL_OUTER_CURVATURE_SCALE;
uniform float HSM_BZL_OUTER_POSITION_Y;
uniform float HSM_BZL_SCALE_OFFSET;
uniform float HSM_BZL_USE_INDEPENDENT_CURVATURE;
uniform float HSM_BZL_USE_INDEPENDENT_SCALE;
uniform float HSM_BZL_WIDTH;
uniform float HSM_CACHE_GRAPHICS_ON;
uniform float HSM_CACHE_UPDATE_INDICATOR_MODE;
uniform float HSM_CORE_RES_SAMPLING_MULT_OPPOSITE_DIR;
uniform float HSM_CORE_RES_SAMPLING_MULT_SCANLINE_DIR;
uniform float HSM_CROP_BLACK_THRESHOLD;
uniform float HSM_CROP_MODE;
uniform float HSM_CROP_PERCENT_BOTTOM;
uniform float HSM_CROP_PERCENT_LEFT;
uniform float HSM_CROP_PERCENT_RIGHT;
uniform float HSM_CROP_PERCENT_TOP;
uniform float HSM_CROP_PERCENT_ZOOM;
uniform float HSM_CRT_BLEND_AMOUNT;
uniform float HSM_CRT_BLEND_MODE;
uniform float HSM_CRT_CURVATURE_SCALE;
uniform float HSM_CRT_SCREEN_BLEND_MODE;
uniform float HSM_CURVATURE_2D_SCALE_LONG_AXIS;
uniform float HSM_CURVATURE_2D_SCALE_SHORT_AXIS;
uniform float HSM_CURVATURE_3D_RADIUS;
uniform float HSM_CURVATURE_3D_TILT_ANGLE_X;
uniform float HSM_CURVATURE_3D_TILT_ANGLE_Y;
uniform float HSM_CURVATURE_3D_VIEW_DIST;
uniform float HSM_CURVATURE_MODE;
uniform float HSM_DOWNSAMPLE_BLUR_OPPOSITE_DIR;
uniform float HSM_DOWNSAMPLE_BLUR_SCANLINE_DIR;
uniform float HSM_DREZ_HSHARP0;
uniform float HSM_DREZ_SIGMA_HV;
uniform float HSM_DREZ_SHAR;
uniform float HSM_DREZ_THRESHOLD_RATIO;
uniform float HSM_DUALSCREEN_CORE_IMAGE_SPLIT_MODE;
uniform float HSM_DUALSCREEN_CORE_IMAGE_SWAP_SCREENS;
uniform float HSM_DUALSCREEN_CORE_IMAGE_SPLIT_OFFSET;
uniform float HSM_DUALSCREEN_MODE;
uniform float HSM_DUALSCREEN_POSITION_OFFSET_BETWEEN_SCREENS;
uniform float HSM_DUALSCREEN_SHIFT_POSITION_WITH_SCALE;
uniform float HSM_DUALSCREEN_VIEWPORT_SPLIT_LOCATION;
uniform float HSM_FAKE_SCANLINE_CURVATURE;
uniform float HSM_FAKE_SCANLINE_INT_SCALE;
uniform float HSM_FAKE_SCANLINE_MODE;
uniform float HSM_FAKE_SCANLINE_OPACITY;
uniform float HSM_FAKE_SCANLINE_RES;
uniform float HSM_FAKE_SCANLINE_RES_MODE;
uniform float HSM_FAKE_SCANLINE_ROLL;
uniform float HSM_FLIP_CORE_HORIZONTAL;
uniform float HSM_FLIP_CORE_VERTICAL;
uniform float HSM_FLIP_VIEWPORT_HORIZONTAL;
uniform float HSM_FLIP_VIEWPORT_VERTICAL;
uniform float HSM_FRM_BLEND_MODE;
uniform float HSM_FRM_COLOR_HUE;
uniform float HSM_FRM_COLOR_SATURATION;
uniform float HSM_FRM_COLOR_VALUE;
uniform float HSM_FRM_INNER_EDGE_HIGHLIGHT;
uniform float HSM_FRM_INNER_EDGE_THICKNESS;
uniform float HSM_FRM_NOISE;
uniform float HSM_FRM_OPACITY;
uniform float HSM_FRM_OUTER_CORNER_RADIUS;
uniform float HSM_FRM_OUTER_CURVATURE_SCALE;
uniform float HSM_FRM_OUTER_EDGE_SHADING;
uniform float HSM_FRM_OUTER_EDGE_THICKNESS;
uniform float HSM_FRM_OUTER_POS_Y;
uniform float HSM_FRM_SHADOW_OPACITY;
uniform float HSM_FRM_SHADOW_WIDTH;
uniform float HSM_FRM_TEXTURE_BLEND_MODE;
uniform float HSM_FRM_TEXTURE_OPACITY;
uniform float HSM_FRM_THICKNESS;
uniform float HSM_FRM_THICKNESS_SCALE_X;
uniform float HSM_FRM_USE_INDEPENDENT_COLOR;
uniform float HSM_GLOBAL_CORNER_RADIUS;
uniform float HSM_GLOBAL_GRAPHICS_BRIGHTNESS;
uniform float HSM_INT_SCALE_MAX_HEIGHT;
uniform float HSM_INT_SCALE_MODE;
uniform float HSM_INT_SCALE_MULTIPLE_OFFSET;
uniform float HSM_INT_SCALE_MULTIPLE_OFFSET_LONG;
uniform float HSM_INTERLACE_EFFECT_SMOOTHNESS_INTERS;
uniform float HSM_INTERLACE_MODE;
uniform float HSM_INTERLACE_SCANLINE_EFFECT;
uniform float HSM_INTERLACE_TRIGGER_RES;
uniform float HSM_INTRO_LOGO_BLEND_MODE;
uniform float HSM_INTRO_LOGO_FADE_IN;
uniform float HSM_INTRO_LOGO_FADE_OUT;
uniform float HSM_INTRO_LOGO_FLIP_VERTICAL;
uniform float HSM_INTRO_LOGO_HEIGHT;
uniform float HSM_INTRO_LOGO_HOLD;
uniform float HSM_INTRO_LOGO_OVER_SOLID_COLOR;
uniform float HSM_INTRO_LOGO_PLACEMENT;
uniform float HSM_INTRO_LOGO_POS_X;
uniform float HSM_INTRO_LOGO_POS_Y;
uniform float HSM_INTRO_LOGO_WAIT;
uniform float HSM_INTRO_NOISE_BLEND_MODE;
uniform float HSM_INTRO_NOISE_FADE_OUT;
uniform float HSM_INTRO_NOISE_HOLD;
uniform float HSM_INTRO_SOLID_BLACK_FADE_OUT;
uniform float HSM_INTRO_SOLID_BLACK_HOLD;
uniform float HSM_INTRO_SOLID_COLOR_BLEND_MODE;
uniform float HSM_INTRO_SOLID_COLOR_FADE_OUT;
uniform float HSM_INTRO_SOLID_COLOR_HOLD;
uniform float HSM_INTRO_SOLID_COLOR_HUE;
uniform float HSM_INTRO_SOLID_COLOR_SAT;
uniform float HSM_INTRO_SOLID_COLOR_VALUE;
uniform float HSM_INTRO_SPEED;
uniform float HSM_INTRO_WHEN_TO_SHOW;
uniform float HSM_LAYERING_DEBUG_MASK_MODE;
uniform float HSM_LED_AMBIENT_LIGHTING_MULTIPLIER;
uniform float HSM_LED_APPLY_AMBIENT_IN_ADD_MODE;
uniform float HSM_LED_BLEND_MODE;
uniform float HSM_LED_BRIGHTNESS;
uniform float HSM_LED_COLORIZE_ON;
uniform float HSM_LED_CUTOUT_MODE;
uniform float HSM_LED_DUALSCREEN_VIS_MODE;
uniform float HSM_LED_FILL_MODE;
uniform float HSM_LED_FOLLOW_FULL_USES_ZOOM;
uniform float HSM_LED_FOLLOW_LAYER;
uniform float HSM_LED_FOLLOW_MODE;
uniform float HSM_LED_GAMMA;
uniform float HSM_LED_HUE;
uniform float HSM_LED_LAYER_ORDER;
uniform float HSM_LED_MASK_MODE;
uniform float HSM_LED_MIPMAPPING_BLEND_BIAS;
uniform float HSM_LED_OPACITY;
uniform float HSM_LED_POS_X;
uniform float HSM_LED_POS_Y;
uniform float HSM_LED_SATURATION;
uniform float HSM_LED_SCALE;
uniform float HSM_LED_SCALE_X;
uniform float HSM_LED_SOURCE_MATTE_TYPE;
uniform float HSM_LED_SPLIT_PRESERVE_CENTER;
uniform float HSM_LED_SPLIT_REPEAT_WIDTH;
uniform float HSM_MONOCHROME_BRIGHTNESS;
uniform float HSM_MONOCHROME_DUALSCREEN_VIS_MODE;
uniform float HSM_MONOCHROME_GAMMA;
uniform float HSM_MONOCHROME_HUE_OFFSET;
uniform float HSM_MONOCHROME_MODE;
uniform float HSM_MONOCHROME_SATURATION;
uniform float HSM_NON_INTEGER_SCALE;
uniform float HSM_NON_INTEGER_SCALE_OFFSET;
uniform float HSM_OVERSCAN_AMOUNT;
uniform float HSM_OVERSCAN_RASTER_BLOOM_AMOUNT;
uniform float HSM_OVERSCAN_RASTER_BLOOM_MODE;
uniform float HSM_OVERSCAN_RASTER_BLOOM_NEUTRAL_RANGE;
uniform float HSM_OVERSCAN_RASTER_BLOOM_NEUTRAL_RANGE_CENTER;
uniform float HSM_OVERSCAN_RASTER_BLOOM_ON;
uniform float HSM_OVERSCAN_X;
uniform float HSM_OVERSCAN_Y;
uniform float HSM_PASS_VIEWER_EMPTY_LINE;
uniform float HSM_PASS_VIEWER_TITLE;
uniform float HSM_PHYSICAL_MONITOR_ASPECT_RATIO;
uniform float HSM_PHYSICAL_MONITOR_DIAGONAL_SIZE;
uniform float HSM_PHYSICAL_MONITOR_DIAGONAL_SIZE;
uniform float HSM_PLACEMENT_IMAGE_MODE;
uniform float HSM_PLACEMENT_IMAGE_USE_HORIZONTAL;
uniform float HSM_POST_CRT_BRIGHTNESS;
uniform float HSM_POTATO_COLORIZE_BRIGHTNESS;
uniform float HSM_POTATO_COLORIZE_CRT_WITH_BG;
uniform float HSM_POTATO_SHOW_BG_OVER_SCREEN;
uniform float HSM_REFLECT_BEZEL_INNER_EDGE_AMOUNT;
uniform float HSM_REFLECT_BEZEL_INNER_EDGE_FULLSCREEN_GLOW;
uniform float HSM_REFLECT_BLUR_FALLOFF_DISTANCE;
uniform float HSM_REFLECT_BLUR_MAX;
uniform float HSM_REFLECT_BLUR_MIN;
uniform float HSM_REFLECT_BLUR_NUM_SAMPLES;
uniform float HSM_REFLECT_BRIGHTNESS_NOISE_BLACK_LEVEL;
uniform float HSM_REFLECT_BRIGHTNESS_NOISE_BRIGHTNESS;
uniform float HSM_REFLECT_CORNER_FADE;
uniform float HSM_REFLECT_CORNER_FADE_DISTANCE;
uniform float HSM_REFLECT_CORNER_INNER_SPREAD;
uniform float HSM_REFLECT_CORNER_OUTER_SPREAD;
uniform float HSM_REFLECT_CORNER_ROTATION_OFFSET_BOTTOM;
uniform float HSM_REFLECT_CORNER_ROTATION_OFFSET_TOP;
uniform float HSM_REFLECT_CORNER_SPREAD_FALLOFF;
uniform float HSM_REFLECT_DIFFUSED_AMOUNT;
uniform float HSM_REFLECT_DIRECT_AMOUNT;
uniform float HSM_REFLECT_FADE_AMOUNT;
uniform float HSM_REFLECT_FRAME_INNER_EDGE_AMOUNT;
uniform float HSM_REFLECT_FRAME_INNER_EDGE_SHARPNESS;
uniform float HSM_REFLECT_FULLSCREEN_GLOW;
uniform float HSM_REFLECT_FULLSCREEN_GLOW_GAMMA;
uniform float HSM_REFLECT_GLOBAL_AMOUNT;
uniform float HSM_REFLECT_GLOBAL_GAMMA_ADJUST;
uniform float HSM_REFLECT_LATERAL_OUTER_FADE_DISTANCE;
uniform float HSM_REFLECT_LATERAL_OUTER_FADE_POSITION;
uniform float HSM_REFLECT_MASK_BLACK_LEVEL;
uniform float HSM_REFLECT_MASK_BRIGHTNESS;
uniform float HSM_REFLECT_MASK_FOLLOW_LAYER;
uniform float HSM_REFLECT_MASK_FOLLOW_MODE;
uniform float HSM_REFLECT_MASK_IMAGE_AMOUNT;
uniform float HSM_REFLECT_MASK_MIPMAPPING_BLEND_BIAS;
uniform float HSM_REFLECT_NOISE_AMOUNT;
uniform float HSM_REFLECT_NOISE_SAMPLE_DISTANCE;
uniform float HSM_REFLECT_NOISE_SAMPLES;
uniform float HSM_REFLECT_RADIAL_FADE_HEIGHT;
uniform float HSM_REFLECT_RADIAL_FADE_WIDTH;
uniform float HSM_REFLECT_SHOW_TUBE_FX_AMOUNT;
uniform float HSM_REFLECT_VIGNETTE_AMOUNT;
uniform float HSM_REFLECT_VIGNETTE_SIZE;
uniform float HSM_RENDER_FOR_SIMPLIFIED_EMPTY_LINE;
uniform float HSM_RENDER_FOR_SIMPLIFIED_TITLE;
uniform float HSM_RENDER_SIMPLE_MASK_TYPE;
uniform float HSM_RENDER_SIMPLE_MODE;
uniform float HSM_RESOLUTION_DEBUG_ON;
uniform float HSM_ROTATE_CORE_IMAGE;
uniform float HSM_SCANLINE_DIRECTION;
uniform float HSM_SCREEN_CORNER_RADIUS_SCALE;
uniform float HSM_SCREEN_POSITION_X;
uniform float HSM_SCREEN_POSITION_Y;
uniform float HSM_SCREEN_REFLECTION_FOLLOW_DIFFUSE_THICKNESS;
uniform float HSM_SCREEN_REFLECTION_POS_X;
uniform float HSM_SCREEN_REFLECTION_POS_Y;
uniform float HSM_SCREEN_REFLECTION_SCALE;
uniform float HSM_SCREEN_VIGNETTE_DUALSCREEN_VIS_MODE;
uniform float HSM_SCREEN_VIGNETTE_IN_REFLECTION;
uniform float HSM_SCREEN_VIGNETTE_ON;
uniform float HSM_SCREEN_VIGNETTE_POWER;
uniform float HSM_SCREEN_VIGNETTE_STRENGTH;
uniform float HSM_SHOW_CRT_ON_TOP_OF_COLORED_GEL;
uniform float HSM_SHOW_PASS_ALPHA;
uniform float HSM_SHOW_PASS_APPLY_SCREEN_COORD;
uniform float HSM_SHOW_PASS_INDEX;
uniform float HSM_SIGNAL_NOISE_AMOUNT;
uniform float HSM_SIGNAL_NOISE_BLACK_LEVEL;
uniform float HSM_SIGNAL_NOISE_ON;
uniform float HSM_SIGNAL_NOISE_SIZE_MODE;
uniform float HSM_SIGNAL_NOISE_SIZE_MULT;
uniform float HSM_SIGNAL_NOISE_TYPE;
uniform float HSM_SINDEN_BORDER_BRIGHTNESS;
uniform float HSM_SINDEN_BORDER_EMPTY_TUBE_COMPENSATION;
uniform float HSM_SINDEN_BORDER_ON;
uniform float HSM_SINDEN_BORDER_THICKNESS;
uniform float HSM_SNAP_TO_CLOSEST_INT_SCALE_TOLERANCE;
uniform float HSM_STATIC_LAYERS_GAMMA;
uniform float HSM_TOP_AMBIENT_LIGHTING_MULTIPLIER;
uniform float HSM_TOP_APPLY_AMBIENT_IN_ADD_MODE;
uniform float HSM_TOP_BLEND_MODE;
uniform float HSM_TOP_BRIGHTNESS;
uniform float HSM_TOP_COLORIZE_ON;
uniform float HSM_TOP_CUTOUT_MODE;
uniform float HSM_TOP_DUALSCREEN_VIS_MODE;
uniform float HSM_TOP_FILL_MODE;
uniform float HSM_TOP_FOLLOW_FULL_USES_ZOOM;
uniform float HSM_TOP_FOLLOW_LAYER;
uniform float HSM_TOP_FOLLOW_MODE;
uniform float HSM_TOP_GAMMA;
uniform float HSM_TOP_HUE;
uniform float HSM_TOP_LAYER_ORDER;
uniform float HSM_TOP_MASK_MODE;
uniform float HSM_TOP_MIPMAPPING_BLEND_BIAS;
uniform float HSM_TOP_OPACITY;
uniform float HSM_TOP_POS_X;
uniform float HSM_TOP_POS_Y;
uniform float HSM_TOP_SATURATION;
uniform float HSM_TOP_SCALE;
uniform float HSM_TOP_SCALE_X;
`;
    }

    const extraUniforms = [paramUniforms, megaBezelVariables]
      .filter(Boolean)
      .join('\n');

    if (extraUniforms) {
      const precisionEnd = output.search(/precision.*?;\s*\n\s*precision.*?;\s*\n|precision.*?;\s*\n/);
      if (precisionEnd !== -1) {
        const precisionMatch = output.substring(precisionEnd).match(/precision.*?;\s*\n/);
        if (precisionMatch) {
          const insertPos = precisionEnd + precisionMatch[0].length;
          output = output.substring(0, insertPos) + '\n' + extraUniforms + '\n' + output.substring(insertPos);
        }
      } else {
        output = extraUniforms + '\n' + output;
      }
    }

    return output;
  }
}
